---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: planktron-manager
  namespace: kube-system
# secrets:
# - name: planktron-manager-token-xyz

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: planktron-manager-role
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
- nonResourceURLs:
  - '*'
  verbs:
  - '*'

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: planktron-manager-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: planktron-manager-role
subjects:
- kind: ServiceAccount
  name: planktron-manager
  namespace: kube-system

---
apiVersion: v1
kind: Secret
metadata:
  name: planktron-manager-token-zx8xj
  namespace: kube-system
type: kubernetes.io/service-account-token
data:
  ca.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMvakNDQWVhZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJeU1UQXlNVEU0TWpZeE1Wb1hEVE15TVRBeE9ERTRNall4TVZvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTTF6Cm14dVEyT0wrZGl6enNCcVU5bUlaQjRYaEt2RHExS29hV2oxdVFmRWVhLzFSY1lKOWthaTVkYjJRbzV6ZXFuUTMKYTdIMm90dkpodGw2bUxrYVU4c3h3NnVuSC9XdEpyUTVTZzBVSmV0MThydXRWaTJlcTlGMTRORUxRRU9zTU9ONwpwa3g2Ymw5YnZrT3FlUk55bzQ1OFpVc3habDJmL1ZzaHhHdFd3Q29XRXAyRzhSSTBvc05MOEhETG9YdjVYVGZGCklzWllhL0lWanEwaXBYRTM5bXFKQjltT2R5dzNNbzJadUNqNSt6SXVJbm5LQXRzWUFLc3ErclhIR0E1bGJFWVcKTHBPTDk3YUJrUmwrNnVubGdBeW5YMEp1M3JhWWRiSEROWDRPYi9lb29mVG5IYll4L0dsbVE1MDZlcFJrRnlXaQpFcEF0MUFuSE9FTUJybTlSSkIwQ0F3RUFBYU5aTUZjd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZHRDkrUW9iZ3o1cHFMMTlqMS9TaDgzeDBJWWhNQlVHQTFVZEVRUU8KTUF5Q0NtdDFZbVZ5Ym1WMFpYTXdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBQ0FxbGw5L3JnNWJFcFdSWUFMTwp5eTFrOFg3aDA0SFlSWEVjaWtydFppZWNuR0VBRW9BcW4vbGxjUGdGQjZRbWtUcDJjYm4yL2ZyektYZmpxbkdQCkhsN0lzQUJOTXN5cFFZMCtLVzFvUDBCL0p1b2U0Z0EvUzJxeHUxbmFveXBkcG1zL0lMb2ZlcmxNWTZJc0Y1a0IKZDVaWFN0WGNqc21XVHNwdjd0R1gveDcvNjcrcTdTTkc5b3FmRTI2VGNhZHB0QzhKT0xNUkIyL296VGFyV3dmbwpHOVh2cWtVbXBWb1owbE96THY2SmJ0SW15bndLZnRVdDgyYUcvZy9Ra3FUZUhrZ2NmMHdLT09sRUd5N2Joc1BIClpVaEdlK2VoTExmUm1aaGtrZkhRYUg2WmZ1eXg4MnYxcjg1emtDOTNod1VyWGdwNW4zcGNjdGlpY292em16ZlkKdG5zPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  namespace: a3ViZS1zeXN0ZW0=
  token: ZXlKaGJHY2lPaUpTVXpJMU5pSXNJbXRwWkNJNklrbE9UbTlIV0hOeVdWbGZlV3c0Vm5SWVQwWkJlbVU0WTJocFJVVkVSekp1Y1RoeE9ISjRUak5MTjBraWZRLmV5SnBjM01pT2lKcmRXSmxjbTVsZEdWekwzTmxjblpwWTJWaFkyTnZkVzUwSWl3aWEzVmlaWEp1WlhSbGN5NXBieTl6WlhKMmFXTmxZV05qYjNWdWRDOXVZVzFsYzNCaFkyVWlPaUpyZFdKbExYTjVjM1JsYlNJc0ltdDFZbVZ5Ym1WMFpYTXVhVzh2YzJWeWRtbGpaV0ZqWTI5MWJuUXZjMlZqY21WMExtNWhiV1VpT2lKd2JHRnVhM1J5YjI0dGJXRnVZV2RsY2kxMGIydGxiaTE2ZURoNGFpSXNJbXQxWW1WeWJtVjBaWE11YVc4dmMyVnlkbWxqWldGalkyOTFiblF2YzJWeWRtbGpaUzFoWTJOdmRXNTBMbTVoYldVaU9pSndiR0Z1YTNSeWIyNHRiV0Z1WVdkbGNpSXNJbXQxWW1WeWJtVjBaWE11YVc4dmMyVnlkbWxqWldGalkyOTFiblF2YzJWeWRtbGpaUzFoWTJOdmRXNTBMblZwWkNJNkltRmxPRE00WVdNNUxUY3dZbUl0TkRWaE5DMWlPRE5rTFdJeU9HRTFNVGMwWXpBMU9DSXNJbk4xWWlJNkluTjVjM1JsYlRwelpYSjJhV05sWVdOamIzVnVkRHByZFdKbExYTjVjM1JsYlRwd2JHRnVhM1J5YjI0dGJXRnVZV2RsY2lKOS56RU5xV2ZNT3o3aUhvVk0wYUFFRlN3eEZBbkEyRlNWdmNMNGdHWGxTNV9aZ3c5Q1p3TmtLc2ZBeFd6bVNibk05WnEyMTM2eWpkRmhFWmxubVg1LVAzaGZwRUZRQkRDQW1ianEtLW92d3Blbi1XdU5pT1JVYW05bWp0eXVQRTNsVjhYZmcydWYyUE40TmdkN09KeGZNUmtSOFhEaC1BVThvUEhTcVVYZjRRYjg4bDFrUm9wd0ZLRFFkb2xjd0lSXzY2aDB5SWE0NlBNQmRBYVg4WjlyX0RGdGVSZ3dIMkpMcGU5SW05d3VLWXNRdkR2NjM3RERSU1c4Zk5TVmEzYXN2UXozRGJKZnJmcVZPWjVEMjFndVNPX05XT1ZZUHRFWHJyVmtuX3dzYUlDUGpRQng2TzNDRzNaRk80MzVZa3hyLWpISFdlX2QxZDhZYkRCSTlGNUx6bnc=
